default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: steindorfer
  timeout: 5000

development:
  <<: *default
  database: GocaseDB
test:
  <<: *default
  database: GocaseDB

production:
  <<: *default
  database: GocaseDB
